{{- if .Release.IsInstall }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
stringData:
  password: {{ include "chrt-6456.password" .}}
{{- end }}